# Generated by Django 3.0.7 on 2020-06-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=20)),
                ('patient_status', models.CharField(max_length=20)),
                ('hospitalization_status', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=200)),
                ('sample_result', models.CharField(max_length=20)),
                ('testing_lab', models.CharField(max_length=200)),
            ],
        ),
    ]
