# Generated by Django 3.0.7 on 2020-06-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate_data', '0002_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='validate_data/incoming/')),
            ],
        ),
    ]
